CREATE TABLE CUSTOMER
(ID INT,
 NAME TEXT NOT NULL,
 AGE  INT  NOT NULL);

ALTER TABLE CUSTOMER ADD PRIMARY KEY (ID);

CREATE SEQUENCE customer_id_seq;
ALTER TABLE CUSTOMER ALTER COLUMN ID SET DEFAULT nextval('customer_id_seq');
ALTER SEQUENCE customer_id_seq OWNED BY CUSTOMER.ID;

INSERT INTO CUSTOMER (NAME, AGE) VALUES ('Denis',38);
INSERT INTO CUSTOMER (NAME, AGE) VALUES ('Tatsiana', 37 ) ;
INSERT INTO CUSTOMER (NAME, AGE) VALUES ('Sofiya', 12 );
INSERT INTO CUSTOMER (NAME, AGE) VALUES ('Matsvej', 10 );